version: '3'

services:
  dbg2:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: getzdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  node:
    container_name: node-sample-demo-c
    image: node-sample-demo
    build: 
      context: ./node-sample
      #dockerfile: ./node-sample/Dockerfile        
    depends_on:
       - dbg2
    restart: always
    environment:
      DB_HOST: dbg2
      DB_USER: user
      DB_PASSWORD: password
volumes:
  db_data:

networks:
  default:
    external:
      name: g-net